name: main
run-name: ${{ github.actor }}
on: [push]
jobs:
  run-main:
    runs-on: ubuntu-latest
    environment: TEST_ENV
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Run main script
        run: python main.py
        env:
          PHONE_NUMBER: ${{ secrets.PHONE_NUMBER }}
